Svaaan/Hushallet

- package-lock.json
- package.json
- src/Navigation/Navigation.tsx
- src/Screen/CreateAccountScreen.tsx
- src/Screen/CreateHomeScreen.tsx
- src/Screen/HomeScreen.tsx
- src/Screen/ProfileScreen.tsx
- src/Screen/ProfileSettingScreen.tsx
- src/Screen/StatisticsScreen.tsx
- src/Screen/TaskScreen.tsx
> added navigations and screens

- App.tsx
- babel.config.js
- data/mockedChores.ts
- data/mockedUsers.ts
- package-lock.json
- package.json
- src/Navigation/Navigation.tsx
- theme/theme.ts
skapat mockad data för chores samt users. 
håller på att testa ut ett theme för skapa tema för hela projectet och har använt mig utav app.tsx för att testa den!.
inget i app.tsx kommer vara kvar när vi väl valt vårt tema.
> mocked data for chores and user, theme and theme testing in app.tsx

- package-lock.json
- package.json
- src/Navigation/RootNavigator.tsx
- src/Screen/SplashScreen.tsx
- src/Screen/StartScreen.tsx
- en användare ska kunna... 
- [ +] Att temafärger används framför hårdkodade färger
- [ +] Jag har kontrollerat att acceptanskraven fungerar
> 27 gör klart startscreen

- package-lock.json
- src/Navigation/RootNavigator.tsx
> Gjort en fix för npm paketet som kraschar program

- src/Component/ChoreChart.tsx
- src/Component/PieChartWithCenteredLabels .tsx
- src/Navigation/HouseholdSwipeNavigator.tsx
- src/Screen/StatisticsScreen.tsx
> Har gjort CSS styling för att likna Figman.

- App.tsx
- data/mockedAccount.ts
- data/mockedHomes.ts
- src/Context/UserContext.tsx
- src/Screen/CreateAccountScreen.tsx
- src/Screen/HomeScreen.tsx
- src/Screen/LoginScreen.tsx
- src/Screen/SplashScreen.tsx
- src/Screen/StartScreen.tsx
> 4 login och registrering

- package-lock.json
- package.json
- src/Navigation/RootNavigator.tsx
- src/Screen/CreateAccountScreen.tsx
- src/Screen/LoginScreen.tsx
Navigerar enligt figma, lägger till styling enligt mall
- [ x] Att temafärger används framför hårdkodade färger
- [x ] Jag har kontrollerat att acceptanskraven fungerar
> 36 fixa och om navigera + addera styling

- App.tsx
- package-lock.json
- package.json
- src/Navigation/HouseholdSwipeNavigator.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/CreateTaskScreen.tsx
> Lagt till create task screen efter mergen igår med david

- data/mockedChoreEvents.ts
- src/Component/ChoreChart.tsx
- src/Navigation/HouseholdSwipeNavigator.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/MonthlyStatisticsScreen.tsx
Gjort en månads vy för Nuvarande månad( gjort kommentarer för hur man gör för Föregående månad ifall David vill hellre ha den)
fin slipat i chorechart så den inte gör nya slices i onödan utan fyller i den som redan finns (gör den större) när en användare har gjort fler events inom den Chore:en (sysslan)
> 44 month view for statistics

- src/Component/BottomButtonComponent.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/CreateAccountScreen.tsx
- src/Screen/JoinHouseholdScreen.tsx
- src/Screen/MyHouseholdsScreen.tsx
> 43 sätta upp screens

- src/Navigation/RootNavigator.tsx
- src/Screen/DisplayUsersScreen.tsx
- src/Screen/EditHouseholdScreen.tsx
> 50 skapa screens som är kvar

- src/Navigation/RootNavigator.tsx
- src/Screen/CreateTaskScreen.tsx
- src/Screen/EditTaskScreen.tsx
- src/Screen/TaskDetailsScreen.tsx
> 71 ändra syssla namn från task till chore i createtasktaskdetailsedittask screens

- App.tsx
- package-lock.json
- package.json
- src/Context/ChoressContext.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/TodayScreen.tsx
gjort TodayScreen med diverse funktioner och försökt få den likna Figma
> 47 create todayscreen

- src/Screen/HouseProfileScreen.tsx
> knapparna till översikt och redigera finns nu

- src/Screen/JoinHouseholdScreen.tsx
> ändrade footer och avatarer

- src/Component/ChooseEmoji.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/JoinHouseholdScreen.tsx
> Fixat till avatarer

- Readme.txt
- src/Screen/HouseProfileScreen.tsx
- src/Screen/MyHouseholdsScreen.tsx
> 91 logconsole på data för debugging och följa vad som sker

- src/Context/HomeContext.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/JoinHouseholdScreen.tsx
Bug: First time it does not function
> added function to join home

- App.tsx
- data/mockedChoreEvents.ts
- src/Component/ChoreChart.tsx
- src/Component/PieChartWithCenteredLabels .tsx
- src/Context/ChoreEventContext.tsx
- src/Navigation/HouseholdSwipeNavigator.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/CurrentWeekStatisticsScreen.tsx
- src/Screen/LastWeekStatisticsScreen.tsx
- src/Screen/MonthlyStatisticsScreen.tsx
- src/Screen/TodayScreen.tsx
- src/Screen/YearlyStatiscticsScreen.tsx
fixat alla charts använder context data
samt today kan både ta context data Profiles, chores, events
> Fixa alla screens använder context samt todayscreen rendering

- src/Context/HomeContext.tsx
- src/Context/ProfileContext.tsx
- src/Screen/JoinHouseholdScreen.tsx
- src/Screen/MyHouseholdsScreen.tsx
can now only join a home if you do not share
an avatar with any connected profile
> done with avatar restriction

- src/Context/HomeContext.tsx
- src/Screen/EditHouseholdScreen.tsx
- src/Screen/MyHouseholdsScreen.tsx
Bug: Going back to MyHouseholds does not update the names. Relogging into the app fixes this
> can now modify household name

- Readme.txt
- data/mockedChoreEvents.ts
- data/mockedProfiles.ts
- src/Navigation/RootNavigator.tsx
- src/Screen/TodayScreen.tsx
lagt in profile i mockprofile för att få ut avatarer och rendera i statistic / todayScreen
> 121 bugg saknar mockprofiles för statistikvyn

- src/Screen/MyHouseholdsScreen.tsx
> Styled the household screen

- data/mockedProfiles.ts
- src/Component/BottomButtonComponent.tsx
- src/Component/ChooseEmoji.tsx
- src/Context/HomeContext.tsx
- src/Screen/CreateAccountScreen.tsx
- src/Screen/CreateHouseholdScreen.tsx
- src/Screen/HouseProfileScreen.tsx
- src/Screen/JoinHouseholdScreen.tsx
- src/Screen/LoginScreen.tsx
- src/Screen/MyHouseholdsScreen.tsx
- src/Screen/TodayScreen.tsx
> 126 fixa style i householdprofile och create account screen

- src/Screen/HouseProfileScreen.tsx
- src/Screen/MyHouseholdsScreen.tsx
- src/Screen/TodayScreen.tsx
> Style klart

- src/Screen/HouseProfileScreen.tsx
> fixat avatar i en cointainer

- src/Screen/CreateHouseholdScreen.tsx
- src/Screen/MyHouseholdsScreen.tsx
> fixed avatars

- src/Screen/TodayScreen.tsx
> today klar igen

- data/mockedChores.ts
- src/Context/ChoressContext.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/EditTaskScreen.tsx
- src/Screen/TaskDetailsScreen.tsx
- src/Screen/TodayScreen.tsx
Gjort så det går att redigera en Chore och få den uppdaterad.
> Edit task to use context instead

- src/Navigation/HouseholdSwipeNavigator.tsx
- src/Screen/CreateTaskScreen.tsx
- src/Screen/CurrentWeekStatisticsScreen.tsx
- src/Screen/EditHouseholdScreen.tsx
- src/Screen/EditTaskScreen.tsx
- src/Screen/LastWeekStatisticsScreen.tsx
- src/Screen/MonthlyStatisticsScreen.tsx
- src/Screen/TodayScreen.tsx
- src/Screen/YearlyStatiscticsScreen.tsx
> städat bort kommentarer

- src/Navigation/RootNavigator.tsx
- src/Screen/ChoreDetailsScreen.tsx
- src/Screen/CreateChoreScreen.tsx
- src/Screen/EditChoreScreen.tsx
- src/Screen/TodayScreen.tsx
> Ändrat från 'Task' till 'Chore'

- data/mockedChores.ts
- src/Context/ChoressContext.tsx
- src/Navigation/RootNavigator.tsx
- src/Screen/ChoreDetailsScreen.tsx
- src/Screen/CreateChoreScreen.tsx
- src/Screen/EditChoreScreen.tsx
- src/Screen/TodayScreen.tsx
> 169 createchore ej ändrat i createchorescreen

- src/Component/Interval.tsx
- src/Screen/ChoreDetailsScreen.tsx
- src/Screen/TodayScreen.tsx
ändrat färger från röd till "Figma röd" samt skrivit om allting till svenska.
Centrerade Intervall siffran med röda cirkeln medans jag var igång.
> changed color and converted text to Swedish

- src/Component/BottomButtonComponent.tsx
- src/Screen/ChoreDetailsScreen.tsx
- src/Screen/HouseProfileScreen.tsx
> Avklarat syns för non owner och båda för owner

- src/Screen/ChoreDetailsScreen.tsx
- src/Screen/MonthlyStatisticsScreen.tsx
- src/Screen/TodayScreen.tsx
removed the function that prevented completing a chore multiple times per day
> Remove function that prevents multiple same avatars same day

- README.md
> Readme för inlämning
